#[derive(Debug)]
pub struct Cite {
    book: Book,
    chapter: u16,
    verse: u16,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Book {
    // Pentateuco
    Genesis,
    Exodo,
    Levitico,
    Numeros,
    Deuteronomio,
    // Históricos
    Josue,
    Jueces,
    Rut,
    Samuel1,
    Samuel2,
    Reyes1,
    Reyes2,
    Cronicas1,
    Cronicas2,
    Esdras,
    Nehemias,
    Ester,
    // Poéticos
    Job,
    Salmos,
    Proverbios,
    Eclesiastes,
    Cantares,
    // Profetas Mayores
    Isaias,
    Jeremias,
    Lamentaciones,
    Ezequiel,
    Daniel,
    // Profetas Menores
    Oseas,
    Joel,
    Amos,
    Abdias,
    Jonas,
    Miqueas,
    Nahum,
    Habacuc,
    Sofonias,
    Hageo,
    Zacarias,
    Malaquias,
    // Evangelios y Hechos
    Mateo,
    Marcos,
    Lucas,
    Juan,
    Hechos,
    // Cartas Paulinas
    Romanos,
    Corintios1,
    Corintios2,
    Galatas,
    Efesios,
    Filipenses,
    Colosenses,
    Tesalonicenses1,
    Tesalonicenses2,
    Timoteo1,
    Timoteo2,
    Tito,
    Filemon,
    // Otras Cartas y Apocalipsis
    Hebreos,
    Santiago,
    Pedro1,
    Pedro2,
    Juan1,
    Juan2,
    Juan3,
    Judas,
    Apocalipsis,
}
