pub static BOOKS: &[(&str, &str)] = &[
    // Pentateuco
    ("Genesis", r"(?i)\b(Genesis|Gen|Gn)\b"),
    ("Exodo", r"(?i)\b(Exodo|Exod|Ex|Exo)\b"),
    ("Levitico", r"(?i)\b(Levitico|Lev|Lv)\b"),
    ("Numeros", r"(?i)\b(Numeros|Num|Nm)\b"),
    ("Deuteronomio", r"(?i)\b(Deuteronomio|Deut|Dt)\b"),
    // Históricos
    ("Josue", r"(?i)\b(Josue|Jos|Js)\b"),
    ("Jueces", r"(?i)\b(Jueces|Jue|Juec|Jz)\b"),
    ("Rut", r"(?i)\b(Rut|Rt)\b"),
    ("1 Samuel", r"(?i)\b(1\s?Samuel|1\s?Sam|1\s?Sm)\b"),
    ("2 Samuel", r"(?i)\b(2\s?Samuel|2\s?Sam|2\s?Sm)\b"),
    ("1 Reyes", r"(?i)\b(1\s?Reyes|1\s?Rey|1\s?R)\b"),
    ("2 Reyes", r"(?i)\b(2\s?Reyes|2\s?Rey|2\s?R)\b"),
    ("1 Cronicas", r"(?i)\b(1\s?Cronicas|1\s?Cro|1\s?Chr)\b"),
    ("2 Cronicas", r"(?i)\b(2\s?Cronicas|2\s?Cro|2\s?Chr)\b"),
    ("Esdras", r"(?i)\b(Esdras|Esd|Ezr)\b"),
    ("Nehemias", r"(?i)\b(Nehemias|Neh|Ne)\b"),
    ("Ester", r"(?i)\b(Ester|Est)\b"),
    // Poéticos
    ("Job", r"(?i)\b(Job|Jb)\b"),
    ("Salmos", r"(?i)\b(Salmos|Sal|Ps)\b"),
    ("Proverbios", r"(?i)\b(Proverbios|Prov|Pr)\b"),
    ("Eclesiastes", r"(?i)\b(Eclesiastes|Ecl|Qo|Ec)\b"),
    ("Cantares", r"(?i)\b(Cantares|Cant|Ct|Can)\b"),
    // Profetas Mayores
    ("Isaias", r"(?i)\b(Isaias|Isa|Is)\b"),
    ("Jeremias", r"(?i)\b(Jeremias|Jer|Jr)\b"),
    ("Lamentaciones", r"(?i)\b(Lamentaciones|Lam|Lm)\b"),
    ("Ezequiel", r"(?i)\b(Ezequiel|Eze|Ez)\b"),
    ("Daniel", r"(?i)\b(Daniel|Dan|Dn)\b"),
    // Profetas Menores
    ("Oseas", r"(?i)\b(Oseas|Ose|Os)\b"),
    ("Joel", r"(?i)\b(Joel|Jl)\b"),
    ("Amos", r"(?i)\b(Amos|Am)\b"),
    ("Abdias", r"(?i)\b(Abdias|Abd|Ab)\b"),
    ("Jonas", r"(?i)\b(Jonas|Jon)\b"),
    ("Miqueas", r"(?i)\b(Miqueas|Miq|Mi)\b"),
    ("Nahum", r"(?i)\b(Nahum|Nah|Na)\b"),
    ("Habacuc", r"(?i)\b(Habacuc|Hab|Ha)\b"),
    ("Sofonias", r"(?i)\b(Sofonias|Sof|Sf)\b"),
    ("Hageo", r"(?i)\b(Hageo|Hag|Hg)\b"),
    ("Zacarias", r"(?i)\b(Zacarias|Zac|Zc)\b"),
    ("Malaquias", r"(?i)\b(Malaquias|Mal|Ml)\b"),
    // Nuevo Testamento - Evangelios y Hechos
    ("Mateo", r"(?i)\b(Mateo|Mat|Mt)\b"),
    ("Marcos", r"(?i)\b(Marcos|Mar|Mc|Mr)\b"),
    ("Lucas", r"(?i)\b(Lucas|Luc|Lc)\b"),
    ("Juan", r"(?i)\b(Juan|Jn)\b"),
    ("Hechos", r"(?i)\b(Hechos|Hch|Ac)\b"),
    // Cartas Paulinas
    ("Romanos", r"(?i)\b(Romanos|Rom|Ro)\b"),
    ("1 Corintios", r"(?i)\b(1\s?Corintios|1\s?Cor|1\s?Co)\b"),
    ("2 Corintios", r"(?i)\b(2\s?Corintios|2\s?Cor|2\s?Co)\b"),
    ("Galatas", r"(?i)\b(Galatas|Gal|Gl)\b"),
    ("Efesios", r"(?i)\b(Efesios|Efe|Ef)\b"),
    ("Filipenses", r"(?i)\b(Filipenses|Fil|Flp)\b"),
    ("Colosenses", r"(?i)\b(Colosenses|Col|Cl)\b"),
    (
        "1 Tesalonicenses",
        r"(?i)\b(1\s?Tesalonicenses|1\s?Tes|1\s?Ts)\b",
    ),
    (
        "2 Tesalonicenses",
        r"(?i)\b(2\s?Tesalonicenses|2\s?Tes|2\s?Ts)\b",
    ),
    ("1 Timoteo", r"(?i)\b(1\s?Timoteo|1\s?Tim|1\s?Tm)\b"),
    ("2 Timoteo", r"(?i)\b(2\s?Timoteo|2\s?Tim|2\s?Tm)\b"),
    ("Tito", r"(?i)\b(Tito|Tit|Tt)\b"),
    ("Filemon", r"(?i)\b(Filemon|Filem|Flm)\b"),
    // Otras Cartas y Apocalipsis
    ("Hebreos", r"(?i)\b(Hebreos|Heb|Hb)\b"),
    ("Santiago", r"(?i)\b(Santiago|Sant|Stgo|Jas)\b"),
    ("1 Pedro", r"(?i)\b(1\s?Pedro|1\s?Pe|1\s?P)\b"),
    ("2 Pedro", r"(?i)\b(2\s?Pedro|2\s?Pe|2\s?P)\b"),
    ("1 Juan", r"(?i)\b(1\s?Juan|1\s?Jn)\b"),
    ("2 Juan", r"(?i)\b(2\s?Juan|2\s?Jn)\b"),
    ("3 Juan", r"(?i)\b(3\s?Juan|3\s?Jn)\b"),
    ("Judas", r"(?i)\b(Judas|Jud|Jd)\b"),
    ("Apocalipsis", r"(?i)\b(Apocalipsis|Apoc|Ap|Rev)\b"),
];
